apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scalable-server
  labels:
    app: scalable-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-server
  template:
    metadata:
      labels:
        app: scalable-server
    spec:
      containers:
      - name: scalable-server
        image: lumeche/scalable-server:latest      
        ports:
        - containerPort: 8081