apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scalable-server
  labels:
    app: scalable-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-server
  template:
    metadata:
      labels:
        app: scalable-server
    spec:
      containers:
      - name: scalable-server
        image: lumeche/scalable-server:latest      
        ports:
        - containerPort: 8081
##########################

apiVersion: v1
kind: Service
metadata:
  name: scalable-server
  labels:
    app: scalable-server
spec:
  type: NodePort
  ports:
  - name: web
    port: 8081
    targetPort: 8081
  selector:
    app: scalable-server
